export  const CHANGE_BILL_CHANNEL = 'CHANGE_BILL_CHANNEL';
export  const CHANGE_BILLS_CHANNEL = 'CHANGE_BILLS_CHANNEL';
export const CHANGE_PERMISSION_TYPE = 'CHANGE_PERMISSION_TYPE';
export const CHANGE_CHECKOFF_TYPE = 'CHANGE_CHECKOFF_TYPE';
export const CHANGE_TRANSFER_TYPE = 'CHANGE_TRANSFER_TYPE';
export const CHANGE_SUBSCRIPTION_ACTION = 'CHANGE_SUBSCRIPTION_ACTION';